// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: api/play/service/v1/play.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowedPlayListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int64 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
}

func (x *AllowedPlayListRequest) Reset() {
	*x = AllowedPlayListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedPlayListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedPlayListRequest) ProtoMessage() {}

func (x *AllowedPlayListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedPlayListRequest.ProtoReflect.Descriptor instead.
func (*AllowedPlayListRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{0}
}

func (x *AllowedPlayListRequest) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

type AllowedPlayListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*AllowedPlayListReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *AllowedPlayListReply) Reset() {
	*x = AllowedPlayListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedPlayListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedPlayListReply) ProtoMessage() {}

func (x *AllowedPlayListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedPlayListReply.ProtoReflect.Descriptor instead.
func (*AllowedPlayListReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{1}
}

func (x *AllowedPlayListReply) GetItems() []*AllowedPlayListReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type RoomPlayListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *RoomPlayListRequest) Reset() {
	*x = RoomPlayListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayListRequest) ProtoMessage() {}

func (x *RoomPlayListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayListRequest.ProtoReflect.Descriptor instead.
func (*RoomPlayListRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{2}
}

func (x *RoomPlayListRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomPlayListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*RoomPlayListReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RoomPlayListReply) Reset() {
	*x = RoomPlayListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayListReply) ProtoMessage() {}

func (x *RoomPlayListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayListReply.ProtoReflect.Descriptor instead.
func (*RoomPlayListReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{3}
}

func (x *RoomPlayListReply) GetItems() []*RoomPlayListReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePlaySortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreatePlaySortRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreatePlaySortRequest) Reset() {
	*x = CreatePlaySortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaySortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaySortRequest) ProtoMessage() {}

func (x *CreatePlaySortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaySortRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaySortRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePlaySortRequest) GetSendBody() *CreatePlaySortRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreatePlaySortReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId int64 `protobuf:"varint,1,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
}

func (x *CreatePlaySortReply) Reset() {
	*x = CreatePlaySortReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaySortReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaySortReply) ProtoMessage() {}

func (x *CreatePlaySortReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaySortReply.ProtoReflect.Descriptor instead.
func (*CreatePlaySortReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePlaySortReply) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

type CreatePlayGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreatePlayGameRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreatePlayGameRequest) Reset() {
	*x = CreatePlayGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameRequest) ProtoMessage() {}

func (x *CreatePlayGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayGameRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePlayGameRequest) GetSendBody() *CreatePlayGameRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreatePlayGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId int64 `protobuf:"varint,1,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
}

func (x *CreatePlayGameReply) Reset() {
	*x = CreatePlayGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameReply) ProtoMessage() {}

func (x *CreatePlayGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameReply.ProtoReflect.Descriptor instead.
func (*CreatePlayGameReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{7}
}

func (x *CreatePlayGameReply) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

type RoomAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *RoomAccountRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *RoomAccountRequest) Reset() {
	*x = RoomAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAccountRequest) ProtoMessage() {}

func (x *RoomAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAccountRequest.ProtoReflect.Descriptor instead.
func (*RoomAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{8}
}

func (x *RoomAccountRequest) GetSendBody() *RoomAccountRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type RoomAccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   int64  `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	RoomType string `protobuf:"bytes,2,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
}

func (x *RoomAccountReply) Reset() {
	*x = RoomAccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAccountReply) ProtoMessage() {}

func (x *RoomAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAccountReply.ProtoReflect.Descriptor instead.
func (*RoomAccountReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{9}
}

func (x *RoomAccountReply) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomAccountReply) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreateRoomRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRoomRequest) GetSendBody() *CreateRoomRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreateRoomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   int64  `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	Account  string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	RoomType string `protobuf:"bytes,3,opt,name=RoomType,proto3" json:"RoomType,omitempty"`
}

func (x *CreateRoomReply) Reset() {
	*x = CreateRoomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReply) ProtoMessage() {}

func (x *CreateRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReply.ProtoReflect.Descriptor instead.
func (*CreateRoomReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRoomReply) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *CreateRoomReply) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CreateRoomReply) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

type CreatePlayGameScoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreatePlayGameScoreRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreatePlayGameScoreRequest) Reset() {
	*x = CreatePlayGameScoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameScoreRequest) ProtoMessage() {}

func (x *CreatePlayGameScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameScoreRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayGameScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePlayGameScoreRequest) GetSendBody() *CreatePlayGameScoreRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreatePlayGameScoreReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId int64 `protobuf:"varint,3,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
}

func (x *CreatePlayGameScoreReply) Reset() {
	*x = CreatePlayGameScoreReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameScoreReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameScoreReply) ProtoMessage() {}

func (x *CreatePlayGameScoreReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameScoreReply.ProtoReflect.Descriptor instead.
func (*CreatePlayGameScoreReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePlayGameScoreReply) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

type CreatePlayGameResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreatePlayGameResultRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreatePlayGameResultRequest) Reset() {
	*x = CreatePlayGameResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameResultRequest) ProtoMessage() {}

func (x *CreatePlayGameResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameResultRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayGameResultRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePlayGameResultRequest) GetSendBody() *CreatePlayGameResultRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreatePlayGameResultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId int64 `protobuf:"varint,3,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
}

func (x *CreatePlayGameResultReply) Reset() {
	*x = CreatePlayGameResultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameResultReply) ProtoMessage() {}

func (x *CreatePlayGameResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameResultReply.ProtoReflect.Descriptor instead.
func (*CreatePlayGameResultReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePlayGameResultReply) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

type CreatePlayGameSortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreatePlayGameSortRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreatePlayGameSortRequest) Reset() {
	*x = CreatePlayGameSortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameSortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameSortRequest) ProtoMessage() {}

func (x *CreatePlayGameSortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameSortRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayGameSortRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePlayGameSortRequest) GetSendBody() *CreatePlayGameSortRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreatePlayGameSortReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId int64 `protobuf:"varint,3,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
}

func (x *CreatePlayGameSortReply) Reset() {
	*x = CreatePlayGameSortReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameSortReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameSortReply) ProtoMessage() {}

func (x *CreatePlayGameSortReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameSortReply.ProtoReflect.Descriptor instead.
func (*CreatePlayGameSortReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{17}
}

func (x *CreatePlayGameSortReply) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

type CreatePlayGameGoalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendBody *CreatePlayGameGoalRequest_SendBody `protobuf:"bytes,1,opt,name=send_body,json=sendBody,proto3" json:"send_body,omitempty"`
}

func (x *CreatePlayGameGoalRequest) Reset() {
	*x = CreatePlayGameGoalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameGoalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameGoalRequest) ProtoMessage() {}

func (x *CreatePlayGameGoalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameGoalRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayGameGoalRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{18}
}

func (x *CreatePlayGameGoalRequest) GetSendBody() *CreatePlayGameGoalRequest_SendBody {
	if x != nil {
		return x.SendBody
	}
	return nil
}

type CreatePlayGameGoalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId int64 `protobuf:"varint,3,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
}

func (x *CreatePlayGameGoalReply) Reset() {
	*x = CreatePlayGameGoalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameGoalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameGoalReply) ProtoMessage() {}

func (x *CreatePlayGameGoalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameGoalReply.ProtoReflect.Descriptor instead.
func (*CreatePlayGameGoalReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{19}
}

func (x *CreatePlayGameGoalReply) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

type GetUserPlayListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserPlayListRequest) Reset() {
	*x = GetUserPlayListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlayListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlayListRequest) ProtoMessage() {}

func (x *GetUserPlayListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlayListRequest.ProtoReflect.Descriptor instead.
func (*GetUserPlayListRequest) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{20}
}

type GetUserPlayListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetUserPlayListReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetUserPlayListReply) Reset() {
	*x = GetUserPlayListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlayListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlayListReply) ProtoMessage() {}

func (x *GetUserPlayListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlayListReply.ProtoReflect.Descriptor instead.
func (*GetUserPlayListReply) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{21}
}

func (x *GetUserPlayListReply) GetItems() []*GetUserPlayListReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type AllowedPlayListReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	StartTime string `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime   string `protobuf:"bytes,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
}

func (x *AllowedPlayListReply_Item) Reset() {
	*x = AllowedPlayListReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowedPlayListReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowedPlayListReply_Item) ProtoMessage() {}

func (x *AllowedPlayListReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowedPlayListReply_Item.ProtoReflect.Descriptor instead.
func (*AllowedPlayListReply_Item) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{1, 0}
}

func (x *AllowedPlayListReply_Item) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AllowedPlayListReply_Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AllowedPlayListReply_Item) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AllowedPlayListReply_Item) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type RoomPlayListReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	StartTime string `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime   string `protobuf:"bytes,4,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
}

func (x *RoomPlayListReply_Item) Reset() {
	*x = RoomPlayListReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomPlayListReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomPlayListReply_Item) ProtoMessage() {}

func (x *RoomPlayListReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomPlayListReply_Item.ProtoReflect.Descriptor instead.
func (*RoomPlayListReply_Item) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RoomPlayListReply_Item) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RoomPlayListReply_Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RoomPlayListReply_Item) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *RoomPlayListReply_Item) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type CreatePlaySortRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PlayType  string `protobuf:"bytes,3,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"`
	SortId    int64  `protobuf:"varint,4,opt,name=sort_id,json=sortId,proto3" json:"sort_id,omitempty"`
	RoomId    int64  `protobuf:"varint,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *CreatePlaySortRequest_SendBody) Reset() {
	*x = CreatePlaySortRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaySortRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaySortRequest_SendBody) ProtoMessage() {}

func (x *CreatePlaySortRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaySortRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreatePlaySortRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CreatePlaySortRequest_SendBody) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreatePlaySortRequest_SendBody) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreatePlaySortRequest_SendBody) GetPlayType() string {
	if x != nil {
		return x.PlayType
	}
	return ""
}

func (x *CreatePlaySortRequest_SendBody) GetSortId() int64 {
	if x != nil {
		return x.SortId
	}
	return 0
}

func (x *CreatePlaySortRequest_SendBody) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type CreatePlayGameRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime string `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   string `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PlayType  string `protobuf:"bytes,3,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"`
	GameId    int64  `protobuf:"varint,4,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	RoomId    int64  `protobuf:"varint,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
}

func (x *CreatePlayGameRequest_SendBody) Reset() {
	*x = CreatePlayGameRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameRequest_SendBody) ProtoMessage() {}

func (x *CreatePlayGameRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreatePlayGameRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CreatePlayGameRequest_SendBody) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CreatePlayGameRequest_SendBody) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CreatePlayGameRequest_SendBody) GetPlayType() string {
	if x != nil {
		return x.PlayType
	}
	return ""
}

func (x *CreatePlayGameRequest_SendBody) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *CreatePlayGameRequest_SendBody) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomAccountRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *RoomAccountRequest_SendBody) Reset() {
	*x = RoomAccountRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomAccountRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomAccountRequest_SendBody) ProtoMessage() {}

func (x *RoomAccountRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomAccountRequest_SendBody.ProtoReflect.Descriptor instead.
func (*RoomAccountRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{8, 0}
}

func (x *RoomAccountRequest_SendBody) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type CreateRoomRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType string `protobuf:"bytes,1,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
}

func (x *CreateRoomRequest_SendBody) Reset() {
	*x = CreateRoomRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest_SendBody) ProtoMessage() {}

func (x *CreateRoomRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{10, 0}
}

func (x *CreateRoomRequest_SendBody) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

type CreatePlayGameScoreRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId    int64  `protobuf:"varint,1,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
	Pay       int64  `protobuf:"varint,2,opt,name=pay,proto3" json:"pay,omitempty"`
	RedScore  int64  `protobuf:"varint,3,opt,name=red_score,json=redScore,proto3" json:"red_score,omitempty"`
	BlueScore int64  `protobuf:"varint,4,opt,name=blue_score,json=blueScore,proto3" json:"blue_score,omitempty"`
	PlayType  string `protobuf:"bytes,5,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"`
}

func (x *CreatePlayGameScoreRequest_SendBody) Reset() {
	*x = CreatePlayGameScoreRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameScoreRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameScoreRequest_SendBody) ProtoMessage() {}

func (x *CreatePlayGameScoreRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameScoreRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreatePlayGameScoreRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{12, 0}
}

func (x *CreatePlayGameScoreRequest_SendBody) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

func (x *CreatePlayGameScoreRequest_SendBody) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

func (x *CreatePlayGameScoreRequest_SendBody) GetRedScore() int64 {
	if x != nil {
		return x.RedScore
	}
	return 0
}

func (x *CreatePlayGameScoreRequest_SendBody) GetBlueScore() int64 {
	if x != nil {
		return x.BlueScore
	}
	return 0
}

func (x *CreatePlayGameScoreRequest_SendBody) GetPlayType() string {
	if x != nil {
		return x.PlayType
	}
	return ""
}

type CreatePlayGameResultRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId   int64  `protobuf:"varint,1,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
	Pay      int64  `protobuf:"varint,2,opt,name=pay,proto3" json:"pay,omitempty"`
	Result   string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	PlayType string `protobuf:"bytes,4,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"`
}

func (x *CreatePlayGameResultRequest_SendBody) Reset() {
	*x = CreatePlayGameResultRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameResultRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameResultRequest_SendBody) ProtoMessage() {}

func (x *CreatePlayGameResultRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameResultRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreatePlayGameResultRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{14, 0}
}

func (x *CreatePlayGameResultRequest_SendBody) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

func (x *CreatePlayGameResultRequest_SendBody) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

func (x *CreatePlayGameResultRequest_SendBody) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CreatePlayGameResultRequest_SendBody) GetPlayType() string {
	if x != nil {
		return x.PlayType
	}
	return ""
}

type CreatePlayGameSortRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId  int64  `protobuf:"varint,1,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
	Pay     int64  `protobuf:"varint,2,opt,name=pay,proto3" json:"pay,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SortId  int64  `protobuf:"varint,4,opt,name=sort_id,json=sortId,proto3" json:"sort_id,omitempty"`
}

func (x *CreatePlayGameSortRequest_SendBody) Reset() {
	*x = CreatePlayGameSortRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameSortRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameSortRequest_SendBody) ProtoMessage() {}

func (x *CreatePlayGameSortRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameSortRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreatePlayGameSortRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{16, 0}
}

func (x *CreatePlayGameSortRequest_SendBody) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

func (x *CreatePlayGameSortRequest_SendBody) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

func (x *CreatePlayGameSortRequest_SendBody) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePlayGameSortRequest_SendBody) GetSortId() int64 {
	if x != nil {
		return x.SortId
	}
	return 0
}

type CreatePlayGameGoalRequest_SendBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayId   int64  `protobuf:"varint,1,opt,name=play_id,json=playId,proto3" json:"play_id,omitempty"`
	Pay      int64  `protobuf:"varint,2,opt,name=pay,proto3" json:"pay,omitempty"`
	TeamId   int64  `protobuf:"varint,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Goal     int64  `protobuf:"varint,4,opt,name=goal,proto3" json:"goal,omitempty"`
	PlayType string `protobuf:"bytes,5,opt,name=play_type,json=playType,proto3" json:"play_type,omitempty"`
}

func (x *CreatePlayGameGoalRequest_SendBody) Reset() {
	*x = CreatePlayGameGoalRequest_SendBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayGameGoalRequest_SendBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayGameGoalRequest_SendBody) ProtoMessage() {}

func (x *CreatePlayGameGoalRequest_SendBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayGameGoalRequest_SendBody.ProtoReflect.Descriptor instead.
func (*CreatePlayGameGoalRequest_SendBody) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{18, 0}
}

func (x *CreatePlayGameGoalRequest_SendBody) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

func (x *CreatePlayGameGoalRequest_SendBody) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

func (x *CreatePlayGameGoalRequest_SendBody) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *CreatePlayGameGoalRequest_SendBody) GetGoal() int64 {
	if x != nil {
		return x.Goal
	}
	return 0
}

func (x *CreatePlayGameGoalRequest_SendBody) GetPlayType() string {
	if x != nil {
		return x.PlayType
	}
	return ""
}

type GetUserPlayListReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlayId    int64  `protobuf:"varint,2,opt,name=PlayId,proto3" json:"PlayId,omitempty"`
	Pay       int64  `protobuf:"varint,3,opt,name=Pay,proto3" json:"Pay,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt string `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
}

func (x *GetUserPlayListReply_Item) Reset() {
	*x = GetUserPlayListReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_play_service_v1_play_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPlayListReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlayListReply_Item) ProtoMessage() {}

func (x *GetUserPlayListReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_play_service_v1_play_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlayListReply_Item.ProtoReflect.Descriptor instead.
func (*GetUserPlayListReply_Item) Descriptor() ([]byte, []int) {
	return file_api_play_service_v1_play_proto_rawDescGZIP(), []int{21, 0}
}

func (x *GetUserPlayListReply_Item) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *GetUserPlayListReply_Item) GetPlayId() int64 {
	if x != nil {
		return x.PlayId
	}
	return 0
}

func (x *GetUserPlayListReply_Item) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

func (x *GetUserPlayListReply_Item) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUserPlayListReply_Item) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_play_service_v1_play_proto protoreflect.FileDescriptor

var file_api_play_service_v1_play_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x16,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x22,
	0xc0, 0x01, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x62,
	0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x13, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x22, 0xba, 0x01, 0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f,
	0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x62, 0x0a, 0x04, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0xff, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x09, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64,
	0x79, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x93, 0x01, 0x0a, 0x08,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x22, 0x2e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49,
	0x64, 0x22, 0xff, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x50, 0x0a, 0x09, 0x73,
	0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x93, 0x01,
	0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x64, 0x22, 0x2e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x49, 0x64, 0x22, 0x94, 0x01, 0x0a, 0x12, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x09, 0x73, 0x65,
	0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x2f, 0x0a, 0x08, 0x53, 0x65, 0x6e,
	0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x23, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x09, 0xfa, 0x42, 0x06, 0x72, 0x04, 0x10, 0x0f, 0x18,
	0x2d, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x46, 0x0a, 0x10, 0x52, 0x6f,
	0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64,
	0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x27, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x5f, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x84, 0x02, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x55, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x38, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x73, 0x65,
	0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x8e, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x61, 0x79, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x72, 0x65, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62,
	0x6c, 0x75, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x62, 0x6c, 0x75, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x22, 0xe1, 0x01, 0x0a,
	0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x39, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x42, 0x6f, 0x64, 0x79, 0x1a, 0x6a, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x34, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x22, 0xdb, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79,
	0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x68, 0x0a, 0x08, 0x53, 0x65,
	0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x70, 0x61,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6f,
	0x72, 0x74, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x22, 0xf2, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x6f,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f,
	0x64, 0x79, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x7f, 0x0a, 0x08,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x70, 0x61, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x67, 0x6f, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x67, 0x6f, 0x61, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x32, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x47,
	0x6f, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x49,
	0x64, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd4, 0x01, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x76, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x61,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x32, 0xc7, 0x0c, 0x0a, 0x04, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x93, 0x01, 0x0a, 0x0f,
	0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x12,
	0x20, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2f, 0x7b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x7d, 0x12, 0x87, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x12, 0x1d, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x2f, 0x7b, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x89, 0x01, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x2a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x6f, 0x72, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x0e, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x3a, 0x09, 0x73, 0x65,
	0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x89, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61,
	0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x6c, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x83, 0x01, 0x0a, 0x0b, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1e, 0x22, 0x11, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x78, 0x0a, 0x0a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x22, 0x09, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x9e, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x2f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x21, 0x22, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f,
	0x62, 0x6f, 0x64, 0x79, 0x12, 0xa2, 0x01, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x28, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x22, 0x22, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c,
	0x61, 0x79, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x3a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x9a, 0x01, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x61, 0x6c,
	0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x6f, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61,
	0x79, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x67, 0x6f, 0x61, 0x6c, 0x3a, 0x09, 0x73, 0x65, 0x6e,
	0x64, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x9a, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x2e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x20, 0x22, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2f, 0x67,
	0x61, 0x6d, 0x65, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x3a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x86, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12, 0x13, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c,
	0x61, 0x79, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x34, 0x0a, 0x13,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x67, 0x6f, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x6c, 0x61, 0x79, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_play_service_v1_play_proto_rawDescOnce sync.Once
	file_api_play_service_v1_play_proto_rawDescData = file_api_play_service_v1_play_proto_rawDesc
)

func file_api_play_service_v1_play_proto_rawDescGZIP() []byte {
	file_api_play_service_v1_play_proto_rawDescOnce.Do(func() {
		file_api_play_service_v1_play_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_play_service_v1_play_proto_rawDescData)
	})
	return file_api_play_service_v1_play_proto_rawDescData
}

var file_api_play_service_v1_play_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_api_play_service_v1_play_proto_goTypes = []interface{}{
	(*AllowedPlayListRequest)(nil),               // 0: api.play.service.v1.AllowedPlayListRequest
	(*AllowedPlayListReply)(nil),                 // 1: api.play.service.v1.AllowedPlayListReply
	(*RoomPlayListRequest)(nil),                  // 2: api.play.service.v1.RoomPlayListRequest
	(*RoomPlayListReply)(nil),                    // 3: api.play.service.v1.RoomPlayListReply
	(*CreatePlaySortRequest)(nil),                // 4: api.play.service.v1.CreatePlaySortRequest
	(*CreatePlaySortReply)(nil),                  // 5: api.play.service.v1.CreatePlaySortReply
	(*CreatePlayGameRequest)(nil),                // 6: api.play.service.v1.CreatePlayGameRequest
	(*CreatePlayGameReply)(nil),                  // 7: api.play.service.v1.CreatePlayGameReply
	(*RoomAccountRequest)(nil),                   // 8: api.play.service.v1.RoomAccountRequest
	(*RoomAccountReply)(nil),                     // 9: api.play.service.v1.RoomAccountReply
	(*CreateRoomRequest)(nil),                    // 10: api.play.service.v1.CreateRoomRequest
	(*CreateRoomReply)(nil),                      // 11: api.play.service.v1.CreateRoomReply
	(*CreatePlayGameScoreRequest)(nil),           // 12: api.play.service.v1.CreatePlayGameScoreRequest
	(*CreatePlayGameScoreReply)(nil),             // 13: api.play.service.v1.CreatePlayGameScoreReply
	(*CreatePlayGameResultRequest)(nil),          // 14: api.play.service.v1.CreatePlayGameResultRequest
	(*CreatePlayGameResultReply)(nil),            // 15: api.play.service.v1.CreatePlayGameResultReply
	(*CreatePlayGameSortRequest)(nil),            // 16: api.play.service.v1.CreatePlayGameSortRequest
	(*CreatePlayGameSortReply)(nil),              // 17: api.play.service.v1.CreatePlayGameSortReply
	(*CreatePlayGameGoalRequest)(nil),            // 18: api.play.service.v1.CreatePlayGameGoalRequest
	(*CreatePlayGameGoalReply)(nil),              // 19: api.play.service.v1.CreatePlayGameGoalReply
	(*GetUserPlayListRequest)(nil),               // 20: api.play.service.v1.GetUserPlayListRequest
	(*GetUserPlayListReply)(nil),                 // 21: api.play.service.v1.GetUserPlayListReply
	(*AllowedPlayListReply_Item)(nil),            // 22: api.play.service.v1.AllowedPlayListReply.Item
	(*RoomPlayListReply_Item)(nil),               // 23: api.play.service.v1.RoomPlayListReply.Item
	(*CreatePlaySortRequest_SendBody)(nil),       // 24: api.play.service.v1.CreatePlaySortRequest.SendBody
	(*CreatePlayGameRequest_SendBody)(nil),       // 25: api.play.service.v1.CreatePlayGameRequest.SendBody
	(*RoomAccountRequest_SendBody)(nil),          // 26: api.play.service.v1.RoomAccountRequest.SendBody
	(*CreateRoomRequest_SendBody)(nil),           // 27: api.play.service.v1.CreateRoomRequest.SendBody
	(*CreatePlayGameScoreRequest_SendBody)(nil),  // 28: api.play.service.v1.CreatePlayGameScoreRequest.SendBody
	(*CreatePlayGameResultRequest_SendBody)(nil), // 29: api.play.service.v1.CreatePlayGameResultRequest.SendBody
	(*CreatePlayGameSortRequest_SendBody)(nil),   // 30: api.play.service.v1.CreatePlayGameSortRequest.SendBody
	(*CreatePlayGameGoalRequest_SendBody)(nil),   // 31: api.play.service.v1.CreatePlayGameGoalRequest.SendBody
	(*GetUserPlayListReply_Item)(nil),            // 32: api.play.service.v1.GetUserPlayListReply.Item
}
var file_api_play_service_v1_play_proto_depIdxs = []int32{
	22, // 0: api.play.service.v1.AllowedPlayListReply.items:type_name -> api.play.service.v1.AllowedPlayListReply.Item
	23, // 1: api.play.service.v1.RoomPlayListReply.items:type_name -> api.play.service.v1.RoomPlayListReply.Item
	24, // 2: api.play.service.v1.CreatePlaySortRequest.send_body:type_name -> api.play.service.v1.CreatePlaySortRequest.SendBody
	25, // 3: api.play.service.v1.CreatePlayGameRequest.send_body:type_name -> api.play.service.v1.CreatePlayGameRequest.SendBody
	26, // 4: api.play.service.v1.RoomAccountRequest.send_body:type_name -> api.play.service.v1.RoomAccountRequest.SendBody
	27, // 5: api.play.service.v1.CreateRoomRequest.send_body:type_name -> api.play.service.v1.CreateRoomRequest.SendBody
	28, // 6: api.play.service.v1.CreatePlayGameScoreRequest.send_body:type_name -> api.play.service.v1.CreatePlayGameScoreRequest.SendBody
	29, // 7: api.play.service.v1.CreatePlayGameResultRequest.send_body:type_name -> api.play.service.v1.CreatePlayGameResultRequest.SendBody
	30, // 8: api.play.service.v1.CreatePlayGameSortRequest.send_body:type_name -> api.play.service.v1.CreatePlayGameSortRequest.SendBody
	31, // 9: api.play.service.v1.CreatePlayGameGoalRequest.send_body:type_name -> api.play.service.v1.CreatePlayGameGoalRequest.SendBody
	32, // 10: api.play.service.v1.GetUserPlayListReply.items:type_name -> api.play.service.v1.GetUserPlayListReply.Item
	0,  // 11: api.play.service.v1.Play.AllowedPlayList:input_type -> api.play.service.v1.AllowedPlayListRequest
	2,  // 12: api.play.service.v1.Play.RoomPlayList:input_type -> api.play.service.v1.RoomPlayListRequest
	4,  // 13: api.play.service.v1.Play.CreatePlaySort:input_type -> api.play.service.v1.CreatePlaySortRequest
	6,  // 14: api.play.service.v1.Play.CreatePlayGame:input_type -> api.play.service.v1.CreatePlayGameRequest
	8,  // 15: api.play.service.v1.Play.RoomAccount:input_type -> api.play.service.v1.RoomAccountRequest
	10, // 16: api.play.service.v1.Play.CreateRoom:input_type -> api.play.service.v1.CreateRoomRequest
	12, // 17: api.play.service.v1.Play.CreatePlayGameScore:input_type -> api.play.service.v1.CreatePlayGameScoreRequest
	14, // 18: api.play.service.v1.Play.CreatePlayGameResult:input_type -> api.play.service.v1.CreatePlayGameResultRequest
	18, // 19: api.play.service.v1.Play.CreatePlayGameGoal:input_type -> api.play.service.v1.CreatePlayGameGoalRequest
	16, // 20: api.play.service.v1.Play.CreatePlayGameSort:input_type -> api.play.service.v1.CreatePlayGameSortRequest
	20, // 21: api.play.service.v1.Play.GetUserPlayList:input_type -> api.play.service.v1.GetUserPlayListRequest
	1,  // 22: api.play.service.v1.Play.AllowedPlayList:output_type -> api.play.service.v1.AllowedPlayListReply
	3,  // 23: api.play.service.v1.Play.RoomPlayList:output_type -> api.play.service.v1.RoomPlayListReply
	5,  // 24: api.play.service.v1.Play.CreatePlaySort:output_type -> api.play.service.v1.CreatePlaySortReply
	7,  // 25: api.play.service.v1.Play.CreatePlayGame:output_type -> api.play.service.v1.CreatePlayGameReply
	9,  // 26: api.play.service.v1.Play.RoomAccount:output_type -> api.play.service.v1.RoomAccountReply
	11, // 27: api.play.service.v1.Play.CreateRoom:output_type -> api.play.service.v1.CreateRoomReply
	13, // 28: api.play.service.v1.Play.CreatePlayGameScore:output_type -> api.play.service.v1.CreatePlayGameScoreReply
	15, // 29: api.play.service.v1.Play.CreatePlayGameResult:output_type -> api.play.service.v1.CreatePlayGameResultReply
	19, // 30: api.play.service.v1.Play.CreatePlayGameGoal:output_type -> api.play.service.v1.CreatePlayGameGoalReply
	17, // 31: api.play.service.v1.Play.CreatePlayGameSort:output_type -> api.play.service.v1.CreatePlayGameSortReply
	21, // 32: api.play.service.v1.Play.GetUserPlayList:output_type -> api.play.service.v1.GetUserPlayListReply
	22, // [22:33] is the sub-list for method output_type
	11, // [11:22] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_play_service_v1_play_proto_init() }
func file_api_play_service_v1_play_proto_init() {
	if File_api_play_service_v1_play_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_play_service_v1_play_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedPlayListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedPlayListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaySortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaySortReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomAccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameScoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameScoreReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameResultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameSortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameSortReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameGoalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameGoalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlayListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlayListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowedPlayListReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomPlayListReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaySortRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomAccountRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameScoreRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameResultRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameSortRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayGameGoalRequest_SendBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_play_service_v1_play_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPlayListReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_play_service_v1_play_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_play_service_v1_play_proto_goTypes,
		DependencyIndexes: file_api_play_service_v1_play_proto_depIdxs,
		MessageInfos:      file_api_play_service_v1_play_proto_msgTypes,
	}.Build()
	File_api_play_service_v1_play_proto = out.File
	file_api_play_service_v1_play_proto_rawDesc = nil
	file_api_play_service_v1_play_proto_goTypes = nil
	file_api_play_service_v1_play_proto_depIdxs = nil
}
