// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: api/game/service/v1/game.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisplayGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DisplayGameRequest) Reset() {
	*x = DisplayGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayGameRequest) ProtoMessage() {}

func (x *DisplayGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayGameRequest.ProtoReflect.Descriptor instead.
func (*DisplayGameRequest) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *DisplayGameRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DisplayGameReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Games []*DisplayGameReply_Game `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
}

func (x *DisplayGameReply) Reset() {
	*x = DisplayGameReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayGameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayGameReply) ProtoMessage() {}

func (x *DisplayGameReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayGameReply.ProtoReflect.Descriptor instead.
func (*DisplayGameReply) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *DisplayGameReply) GetGames() []*DisplayGameReply_Game {
	if x != nil {
		return x.Games
	}
	return nil
}

type GetGameListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGameListRequest) Reset() {
	*x = GetGameListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListRequest) ProtoMessage() {}

func (x *GetGameListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListRequest.ProtoReflect.Descriptor instead.
func (*GetGameListRequest) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{2}
}

type GetGameListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*GetGameListReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *GetGameListReply) Reset() {
	*x = GetGameListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReply) ProtoMessage() {}

func (x *GetGameListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReply.ProtoReflect.Descriptor instead.
func (*GetGameListReply) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameListReply) GetItems() []*GetGameListReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetGameSortListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGameSortListRequest) Reset() {
	*x = GetGameSortListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameSortListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSortListRequest) ProtoMessage() {}

func (x *GetGameSortListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSortListRequest.ProtoReflect.Descriptor instead.
func (*GetGameSortListRequest) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{4}
}

type GetGameSortListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sorts []*GetGameSortListReply_Sort `protobuf:"bytes,1,rep,name=sorts,proto3" json:"sorts,omitempty"`
}

func (x *GetGameSortListReply) Reset() {
	*x = GetGameSortListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameSortListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSortListReply) ProtoMessage() {}

func (x *GetGameSortListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSortListReply.ProtoReflect.Descriptor instead.
func (*GetGameSortListReply) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameSortListReply) GetSorts() []*GetGameSortListReply_Sort {
	if x != nil {
		return x.Sorts
	}
	return nil
}

type GetTeamListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTeamListRequest) Reset() {
	*x = GetTeamListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamListRequest) ProtoMessage() {}

func (x *GetTeamListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamListRequest.ProtoReflect.Descriptor instead.
func (*GetTeamListRequest) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{6}
}

type GetTeamListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Teams []*GetTeamListReply_Team `protobuf:"bytes,1,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *GetTeamListReply) Reset() {
	*x = GetTeamListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamListReply) ProtoMessage() {}

func (x *GetTeamListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamListReply.ProtoReflect.Descriptor instead.
func (*GetTeamListReply) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *GetTeamListReply) GetTeams() []*GetTeamListReply_Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type DisplayGameReply_Game struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId int64                         `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Name   string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Teams  []*DisplayGameReply_Game_Team `protobuf:"bytes,3,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *DisplayGameReply_Game) Reset() {
	*x = DisplayGameReply_Game{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayGameReply_Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayGameReply_Game) ProtoMessage() {}

func (x *DisplayGameReply_Game) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayGameReply_Game.ProtoReflect.Descriptor instead.
func (*DisplayGameReply_Game) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DisplayGameReply_Game) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *DisplayGameReply_Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DisplayGameReply_Game) GetTeams() []*DisplayGameReply_Game_Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type DisplayGameReply_Game_Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId   int64  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName string `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	TeamType string `protobuf:"bytes,3,opt,name=team_type,json=teamType,proto3" json:"team_type,omitempty"`
}

func (x *DisplayGameReply_Game_Team) Reset() {
	*x = DisplayGameReply_Game_Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisplayGameReply_Game_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisplayGameReply_Game_Team) ProtoMessage() {}

func (x *DisplayGameReply_Game_Team) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisplayGameReply_Game_Team.ProtoReflect.Descriptor instead.
func (*DisplayGameReply_Game_Team) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *DisplayGameReply_Game_Team) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *DisplayGameReply_Game_Team) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *DisplayGameReply_Game_Team) GetTeamType() string {
	if x != nil {
		return x.TeamType
	}
	return ""
}

type GetGameListReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId        int64                         `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Name          string                        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime     string                        `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                        `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	UpEndTime     string                        `protobuf:"bytes,5,opt,name=up_end_time,json=upEndTime,proto3" json:"up_end_time,omitempty"`
	DownStartTime string                        `protobuf:"bytes,6,opt,name=down_start_time,json=downStartTime,proto3" json:"down_start_time,omitempty"`
	Teams         []*GetGameListReply_Item_Team `protobuf:"bytes,7,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *GetGameListReply_Item) Reset() {
	*x = GetGameListReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReply_Item) ProtoMessage() {}

func (x *GetGameListReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReply_Item.ProtoReflect.Descriptor instead.
func (*GetGameListReply_Item) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetGameListReply_Item) GetGameId() int64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *GetGameListReply_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGameListReply_Item) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *GetGameListReply_Item) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *GetGameListReply_Item) GetUpEndTime() string {
	if x != nil {
		return x.UpEndTime
	}
	return ""
}

func (x *GetGameListReply_Item) GetDownStartTime() string {
	if x != nil {
		return x.DownStartTime
	}
	return ""
}

func (x *GetGameListReply_Item) GetTeams() []*GetGameListReply_Item_Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

type GetGameListReply_Item_Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId   int64  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName string `protobuf:"bytes,2,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
	TeamType string `protobuf:"bytes,3,opt,name=team_type,json=teamType,proto3" json:"team_type,omitempty"`
}

func (x *GetGameListReply_Item_Team) Reset() {
	*x = GetGameListReply_Item_Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameListReply_Item_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameListReply_Item_Team) ProtoMessage() {}

func (x *GetGameListReply_Item_Team) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameListReply_Item_Team.ProtoReflect.Descriptor instead.
func (*GetGameListReply_Item_Team) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *GetGameListReply_Item_Team) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetGameListReply_Item_Team) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

func (x *GetGameListReply_Item_Team) GetTeamType() string {
	if x != nil {
		return x.TeamType
	}
	return ""
}

type GetGameSortListReply_Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortId   int64  `protobuf:"varint,1,opt,name=sort_id,json=sortId,proto3" json:"sort_id,omitempty"`
	SortType string `protobuf:"bytes,2,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"`
	SortName string `protobuf:"bytes,3,opt,name=sort_name,json=sortName,proto3" json:"sort_name,omitempty"`
	EndTime  string `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *GetGameSortListReply_Sort) Reset() {
	*x = GetGameSortListReply_Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameSortListReply_Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameSortListReply_Sort) ProtoMessage() {}

func (x *GetGameSortListReply_Sort) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameSortListReply_Sort.ProtoReflect.Descriptor instead.
func (*GetGameSortListReply_Sort) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetGameSortListReply_Sort) GetSortId() int64 {
	if x != nil {
		return x.SortId
	}
	return 0
}

func (x *GetGameSortListReply_Sort) GetSortType() string {
	if x != nil {
		return x.SortType
	}
	return ""
}

func (x *GetGameSortListReply_Sort) GetSortName() string {
	if x != nil {
		return x.SortName
	}
	return ""
}

func (x *GetGameSortListReply_Sort) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type GetTeamListReply_Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeamId   int64  `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TeamName string `protobuf:"bytes,3,opt,name=team_name,json=teamName,proto3" json:"team_name,omitempty"`
}

func (x *GetTeamListReply_Team) Reset() {
	*x = GetTeamListReply_Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_game_service_v1_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTeamListReply_Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeamListReply_Team) ProtoMessage() {}

func (x *GetTeamListReply_Team) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_service_v1_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeamListReply_Team.ProtoReflect.Descriptor instead.
func (*GetTeamListReply_Team) Descriptor() ([]byte, []int) {
	return file_api_game_service_v1_game_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetTeamListReply_Team) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *GetTeamListReply_Team) GetTeamName() string {
	if x != nil {
		return x.TeamName
	}
	return ""
}

var File_api_game_service_v1_game_proto protoreflect.FileDescriptor

var file_api_game_service_v1_game_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x13, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x47, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xac, 0x02,
	0x0a, 0x10, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x40, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x05, 0x67,
	0x61, 0x6d, 0x65, 0x73, 0x1a, 0xd5, 0x01, 0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x45, 0x0a, 0x05, 0x74, 0x65,
	0x61, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d,
	0x73, 0x1a, 0x59, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xae, 0x03, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xd7, 0x02, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x75, 0x70, 0x5f,
	0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x64, 0x6f, 0x77,
	0x6e, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x64, 0x6f, 0x77, 0x6e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x45, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x54, 0x65, 0x61,
	0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x1a, 0x59, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d,
	0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61,
	0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65,
	0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f,
	0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd2, 0x01,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x05, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x05, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x1a, 0x74, 0x0a, 0x04,
	0x53, 0x6f, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6f,
	0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a,
	0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x1a,
	0x3c, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0xf6, 0x03,
	0x0a, 0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x7f, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x67, 0x61, 0x6d, 0x65,
	0x2f, 0x7b, 0x74, 0x79, 0x70, 0x65, 0x7d, 0x12, 0x71, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x75, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x54, 0x65, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x61, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x10, 0x12, 0x0e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x2f, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x82, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x2f, 0x73, 0x6f, 0x72, 0x74, 0x73, 0x42, 0x34, 0x0a, 0x13, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a,
	0x1b, 0x67, 0x6f, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_game_service_v1_game_proto_rawDescOnce sync.Once
	file_api_game_service_v1_game_proto_rawDescData = file_api_game_service_v1_game_proto_rawDesc
)

func file_api_game_service_v1_game_proto_rawDescGZIP() []byte {
	file_api_game_service_v1_game_proto_rawDescOnce.Do(func() {
		file_api_game_service_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_game_service_v1_game_proto_rawDescData)
	})
	return file_api_game_service_v1_game_proto_rawDescData
}

var file_api_game_service_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_game_service_v1_game_proto_goTypes = []interface{}{
	(*DisplayGameRequest)(nil),         // 0: api.game.service.v1.DisplayGameRequest
	(*DisplayGameReply)(nil),           // 1: api.game.service.v1.DisplayGameReply
	(*GetGameListRequest)(nil),         // 2: api.game.service.v1.GetGameListRequest
	(*GetGameListReply)(nil),           // 3: api.game.service.v1.GetGameListReply
	(*GetGameSortListRequest)(nil),     // 4: api.game.service.v1.GetGameSortListRequest
	(*GetGameSortListReply)(nil),       // 5: api.game.service.v1.GetGameSortListReply
	(*GetTeamListRequest)(nil),         // 6: api.game.service.v1.GetTeamListRequest
	(*GetTeamListReply)(nil),           // 7: api.game.service.v1.GetTeamListReply
	(*DisplayGameReply_Game)(nil),      // 8: api.game.service.v1.DisplayGameReply.Game
	(*DisplayGameReply_Game_Team)(nil), // 9: api.game.service.v1.DisplayGameReply.Game.Team
	(*GetGameListReply_Item)(nil),      // 10: api.game.service.v1.GetGameListReply.Item
	(*GetGameListReply_Item_Team)(nil), // 11: api.game.service.v1.GetGameListReply.Item.Team
	(*GetGameSortListReply_Sort)(nil),  // 12: api.game.service.v1.GetGameSortListReply.Sort
	(*GetTeamListReply_Team)(nil),      // 13: api.game.service.v1.GetTeamListReply.Team
}
var file_api_game_service_v1_game_proto_depIdxs = []int32{
	8,  // 0: api.game.service.v1.DisplayGameReply.games:type_name -> api.game.service.v1.DisplayGameReply.Game
	10, // 1: api.game.service.v1.GetGameListReply.items:type_name -> api.game.service.v1.GetGameListReply.Item
	12, // 2: api.game.service.v1.GetGameSortListReply.sorts:type_name -> api.game.service.v1.GetGameSortListReply.Sort
	13, // 3: api.game.service.v1.GetTeamListReply.teams:type_name -> api.game.service.v1.GetTeamListReply.Team
	9,  // 4: api.game.service.v1.DisplayGameReply.Game.teams:type_name -> api.game.service.v1.DisplayGameReply.Game.Team
	11, // 5: api.game.service.v1.GetGameListReply.Item.teams:type_name -> api.game.service.v1.GetGameListReply.Item.Team
	0,  // 6: api.game.service.v1.Game.DisplayGame:input_type -> api.game.service.v1.DisplayGameRequest
	2,  // 7: api.game.service.v1.Game.GetGameList:input_type -> api.game.service.v1.GetGameListRequest
	6,  // 8: api.game.service.v1.Game.GetTeamList:input_type -> api.game.service.v1.GetTeamListRequest
	4,  // 9: api.game.service.v1.Game.GetGameSortList:input_type -> api.game.service.v1.GetGameSortListRequest
	1,  // 10: api.game.service.v1.Game.DisplayGame:output_type -> api.game.service.v1.DisplayGameReply
	3,  // 11: api.game.service.v1.Game.GetGameList:output_type -> api.game.service.v1.GetGameListReply
	7,  // 12: api.game.service.v1.Game.GetTeamList:output_type -> api.game.service.v1.GetTeamListReply
	5,  // 13: api.game.service.v1.Game.GetGameSortList:output_type -> api.game.service.v1.GetGameSortListReply
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_game_service_v1_game_proto_init() }
func file_api_game_service_v1_game_proto_init() {
	if File_api_game_service_v1_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_game_service_v1_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayGameReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameSortListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameSortListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayGameReply_Game); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisplayGameReply_Game_Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameListReply_Item_Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameSortListReply_Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_game_service_v1_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTeamListReply_Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_game_service_v1_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_game_service_v1_game_proto_goTypes,
		DependencyIndexes: file_api_game_service_v1_game_proto_depIdxs,
		MessageInfos:      file_api_game_service_v1_game_proto_msgTypes,
	}.Build()
	File_api_game_service_v1_game_proto = out.File
	file_api_game_service_v1_game_proto_rawDesc = nil
	file_api_game_service_v1_game_proto_goTypes = nil
	file_api_game_service_v1_game_proto_depIdxs = nil
}
