// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"goal/app/admin/service/internal/biz"
	"goal/app/admin/service/internal/conf"
	"goal/app/admin/service/internal/data"
	"goal/app/admin/service/internal/server"
	"goal/app/admin/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData)
	client := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client)
	if err != nil {
		return nil, nil, err
	}
	playRepo := data.NewPlayRepo(dataData, logger)
	playGameRelRepo := data.NewPlayGameRelRepo(dataData, logger)
	playGameScoreUserRelRepo := data.NewPlayGameScoreUserRelRepo(dataData, logger)
	gameRepo := data.NewGameRepo(dataData, logger)
	userBalanceRepo := data.NewUserBalanceRepo(dataData, logger)
	userProxyRepo := data.NewUserProxyRepo(dataData, logger)
	userInfoRepo := data.NewUserInfoRepo(dataData, logger)
	transaction := data.NewTransaction(dataData)
	playUseCase := biz.NewPlayUseCase(playRepo, playGameRelRepo, playGameScoreUserRelRepo, gameRepo, userBalanceRepo, userProxyRepo, userInfoRepo, transaction, logger)
	playService := service.NewPlayService(playUseCase, logger)
	gameUseCase := biz.NewGameUseCase(gameRepo, logger)
	gameService := service.NewGameService(gameUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, playService, gameService, logger)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
